@echo off
echo Starting the Digital Aptitude backend server...
start cmd /k "py -m pip install -r requirements.txt && py api\index.py || pause"
echo Waiting for server to start...
ping 127.0.0.1 -n 5 > nul
echo Opening the frontend in your browser...
start http://127.0.0.1:5000
exit